### PR TITLE
Include the Mapper and Model applications in a library.

### PR DESCRIPTION
**Pull request by gilbertmike**
Include the Mapper and Model applications in a new library by:

1. Rename the applications from `Application` to `application::Mapper` or `application::Model` to avoid name collision. This also adds the `application` namespace.
2. Include the sources for the mapper and model in a new library, called `timeloop-applications`.

Note that code that links to `timeloop-applications` also needs to link to `timeloop-mapper`.

**Known Issues**
- Writing to files does not seem to work well (at least, as is) when calling from Python through PyBind11. A solution is to refactor the part of `Run()` that writes to files and just don't call that in the Python version.

### CODE REVIEW

**Comment by angshuman-parashar** [comment]
Build fails on MacOS Ventura 13.6.6, Macbook Pro M1, clang version 14.0.3 (clang-1403.0.22.14.1), target arm64-apple-darwin22.6.0.

Log attached.
[log.txt](https://github.com/NVlabs/timeloop/files/15503830/log.txt)

**Comment by gilbertmike** [comment]
This seems to be caused by the way I'm including symbols in the libraries. I'll try including the symbols in `timeloop-mapper` in `timeloop-applications`.

**Comment by angshuman-parashar** [comment]
```
src/applications/mapper/mapper.cpp:395:41: error: use of undeclared identifier 'oaves_prefix'
                                        oaves_prefix,
                                        ^
```

**Comment by gilbertmike** [comment]
Yes, I thought I moved all the file printing away since PyTimeloop stopped crashing, but I realized `MapperThread` also does a bunch of printing. Somehow these do not crash PyTimeloop so I did not catch them at first. I'm looking into it.

**Comment by angshuman-parashar** [comment]
Regression test passed. Merging.

**Pull request merged**
