### PR TITLE
YAML Setters for CompoundConfigNode

### PR DESCRIPTION
**Pull request by rengzhengcodes**
This change implements YAML-only setters to CompoundConfigNode. It's accompanied by unit tests for the existing lookup resolution functions and unit tests for the setters themselves to ensure expected behavior is maintained in the future.

The lookupValue, lookupArrayValue, and getMapKeys functions have been modified slightly to promise that they ensure the state of the CompoundConfigNode stays constant when accessing a value.

### CODE REVIEW

**Comment by gilbertmike** [comment]
**Motivation**
This commit makes the `CompoundConfig` class *mutable*. We hope that this will make it possible for PyTimeloop to modify `CompoundConfig` directly instead of ser-desing every input into YAML.

**Changes**
Reng already mentioned above.

**Comment by angshuman-parashar** [comment]
I like the unit test, but I think we need to discuss a convention for the directory structure for unit tests. But the present location for the .cpp is reasonable and may end up being our convention.

However, I don't want the YAML files in this repo. I'd like to keep all files in this repo to be under the NVIDIA BSD license. 

License issues aside, these files (and even the directory structure) is a deep-copy of the files in the timeloop-accelergy-exercises repository, which is also not great. Perhaps you could add a README.md in that directory with a pointer to the other repo?

**Comment by angshuman-parashar** [comment]
In principle I agree that a submodule is a great approach. But I have two concerns: (1) the submodule will download the _entire_ exercises repo inline. More importantly, (2) I'm still a little uncomfortable with auto-importing a codebase with a different license. I can check with legal, but in the meantime I really prefer the manual option (i.e., ask users to manually checkout the other repo if they want to perform unit testing). Hope that's acceptable for now.

**Comment by angshuman-parashar** [comment]
Clang is throwing the following error:
```src/unit-tests/compound-config/test-compound-config.cpp:354:66: error: adding 'const YAML::NodeType::value' to a string does not append to the string [-Werror,-Wstring-plus-int]
            throw std::invalid_argument("YAML type is invalid: " + TYPE);
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
src/unit-tests/compound-config/test-compound-config.cpp:354:66: note: use array indexing to silence this warning
            throw std::invalid_argument("YAML type is invalid: " + TYPE);
                                                                 ^
                                        &                        [     ]
```
I assume you're trying to concatenate the strings here? If so I think you need to typecast the constant string to std::string. If you agree I can try it out on my end and let you know if it makes clang happy.

**Comment by angshuman-parashar** [comment]
Builds cleanly with clang now. Thank you! Merged.

**Pull request merged**
