### PR TITLE
Add ruby mapspace

### PR DESCRIPTION
**Pull request by fisherxue**
Add ruby mapspace from https://github.com/MarkHoreni/timeloop

Enable with:
`
mapspace:
  template: ruby
`

### CODE REVIEW

**Comment by angshuman-parashar** [comment]
@fisherxue Thanks very much for working on this.
I do have a few concerns:
- The cycle patch added in 94870a8ee78da782efc2aea4c6bfdca053991da2 (and ef2bc9a1e2ad2b8bcba8d6475f891fa651f2a8e4?) uses a very naive product of temporal loop bounds to determine arithmetic cycles. I believe this may break sparse analysis. @nellie-wu could you confirm?
- In any case we want to avoid counting a microarchitectural stat like `cycles` inside nest-analysis. The variable should be renamed to a more abstract name (e.g., `temporal_nonresidual_product`), which the Arithmetic class can then use to derive `cycles`. Let's discuss this and come up with a clean solution.
- Commit ef2bc9a1e2ad2b8bcba8d6475f891fa651f2a8e4 has a whole-file diff in `buffer.hpp`. Any idea what's happening here?

**Comment by fisherxue** [comment]
1. Confirming now that sparse analysis seems to be broken. 
3. Not sure why it's indicating a full diff because nothing seems to have changed.

**Comment by angshuman-parashar** [comment]
@fisherxue is the new code using CRLF instead of LF? If so could you run dos2unix and fix that?

I'll talk to @nellie-wu about the sparse cycle counts.

**Comment by angshuman-parashar** [comment]
Closing. Changes in this PR were carefully hand-merged into the `ruby` branch in this repo, which was in turn merged into `master` in d128b305cefaf743db49cf3d4fa5f41253db65c2.

**Pull request closed without merging**
