### PR TITLE
 ISL-based Nest Analysis from LoopTree

### PR DESCRIPTION
**Pull request by gilbertmike**
**Motivation**
ISL-based analysis enables a wider range of features in the long term. Hopefully, this also helps to integrate LoopTree, which is ISL-based.

**Summary of Changes**
- Addition of ISL-based nest analysis (see isl-nest-analysis.hpp and its dependencies)
- Behavior of multicast analysis is changed. Hops count is different when using `TIMELOOP_MULTICAST_MODEL=PRECISE`. I believe this version is more accurate and consistent.
- Timeloop must now be built with the `--with-isl` flag.
- Certain fused-layer analyses are in place, although these are still in heavy development and are not exposed to the user in this build.

### CODE REVIEW

**Comment by gilbertmike** [comment]
1. It built fine on my end. Could you send me more information? The compiler version is probably all I need.
2. I use `barvinok` methods in `spatial-analysis.cpp` and `isl-to-legacy-analysis.cpp`. I'm putting locks around those calls. It's in an in-progress commit.

**Comment by gilbertmike** [comment]
Oh, I just didn't understand the error message before. I agree with initializing it to `false`. In fact, that's how it should behave. I'll include this in my next commit.

It seems strange that `barvinok` is not thread-safe since each evaluation is independent of the other and there is no shared data. I feel like there should be a solution other than serializing it. For now, that seems to solve the issue.

If this information helps, the calls to `barvinok` routines happen at the end of analyses when we need to get the size of a set so we can give the numerical results to the models. This process makes up the most convoluted parts of the code and the one causing the bug I found recently.

**Comment by angshuman-parashar** [comment]
clang is detecting a unique_ptr dealloc error (see attachment).
Screenshot 2023-07-17 at 6 18 06 PM

**Comment by gilbertmike** [comment]
I see the error. `SimpleLinkTransfer` should be final. I'll update.

**Pull request merged**
